"""empty message

Revision ID: 2f19250fdb2c
Revises: 305715f80455
Create Date: 2019-09-28 16:54:11.831536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f19250fdb2c'
down_revision = '305715f80455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_type', sa.String(length=140), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user_basic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_basic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_timestamp'), 'mission', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mission_timestamp'), table_name='mission')
    op.drop_table('mission')
    # ### end Alembic commands ###
