"""followers

Revision ID: 305715f80455
Revises: cc7813f7769c
Create Date: 2019-09-22 23:29:25.065975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305715f80455'
down_revision = 'cc7813f7769c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_basic.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user_basic.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
