"""empty message

Revision ID: 3c1d92b84dc9
Revises: b73978e39edf
Create Date: 2019-10-09 15:52:12.934525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1d92b84dc9'
down_revision = 'b73978e39edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('active', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission', 'active')
    # ### end Alembic commands ###
