"""empty message

Revision ID: 85e9e7ce60c0
Revises: d56c90066dca
Create Date: 2019-10-10 22:47:32.633493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e9e7ce60c0'
down_revision = 'd56c90066dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physio_log', sa.Column('physio_subtype', sa.String(length=140), nullable=True))
    op.add_column('physio_log', sa.Column('physio_verify', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('category', sa.String(length=140), nullable=True))
    op.add_column('transaction', sa.Column('transaction_comment', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transaction_comment')
    op.drop_column('post', 'category')
    op.drop_column('physio_log', 'physio_verify')
    op.drop_column('physio_log', 'physio_subtype')
    # ### end Alembic commands ###
