"""empty message

Revision ID: 910a04130c64
Revises: 2f19250fdb2c
Create Date: 2019-09-28 17:16:55.969208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910a04130c64'
down_revision = '2f19250fdb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mission_creator_id_fkey', 'mission', type_='foreignkey')
    op.drop_column('mission', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mission_creator_id_fkey', 'mission', 'user_basic', ['creator_id'], ['id'])
    # ### end Alembic commands ###
