"""empty message

Revision ID: b73978e39edf
Revises: d5e747d48a42
Create Date: 2019-10-09 00:32:50.565643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73978e39edf'
down_revision = 'd5e747d48a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physio_log', sa.Column('mission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'physio_log', 'mission', ['mission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'physio_log', type_='foreignkey')
    op.drop_column('physio_log', 'mission_id')
    # ### end Alembic commands ###
