"""empty message

Revision ID: d56c90066dca
Revises: 3c1d92b84dc9
Create Date: 2019-10-09 16:56:17.819981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56c90066dca'
down_revision = '3c1d92b84dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('level', sa.String(length=140), nullable=True))
    op.drop_column('mission', 'mission_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('mission_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('mission', 'level')
    # ### end Alembic commands ###
