"""empty message

Revision ID: d5e747d48a42
Revises: 72b8d6801b2f
Create Date: 2019-10-08 18:31:33.072892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e747d48a42'
down_revision = '72b8d6801b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('mission_level', sa.Integer(), nullable=True))
    op.add_column('mission', sa.Column('prize', sa.Float(), nullable=True))
    op.drop_constraint('mission_user_id_fkey', 'mission', type_='foreignkey')
    op.drop_column('mission', 'user_id')
    op.add_column('user_basic', sa.Column('mission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_basic', 'mission', ['mission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_basic', type_='foreignkey')
    op.drop_column('user_basic', 'mission_id')
    op.add_column('mission', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mission_user_id_fkey', 'mission', 'user_basic', ['user_id'], ['id'])
    op.drop_column('mission', 'prize')
    op.drop_column('mission', 'mission_level')
    # ### end Alembic commands ###
