"""users table

Revision ID: d6c630b1f8f7
Revises: 
Create Date: 2019-09-22 14:50:08.969126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6c630b1f8f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_basic_email'), 'user_basic', ['email'], unique=True)
    op.create_index(op.f('ix_user_basic_username'), 'user_basic', ['username'], unique=True)
    op.drop_table('UserData')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserData',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"UserData_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('CreateDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='UserData_pkey')
    )
    op.drop_index(op.f('ix_user_basic_username'), table_name='user_basic')
    op.drop_index(op.f('ix_user_basic_email'), table_name='user_basic')
    op.drop_table('user_basic')
    # ### end Alembic commands ###
